[package]
name = "dragonfly-client-storage"
description = "Storage for the dragonfly client"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
dragonfly-client-core.workspace = true
dragonfly-client-config.workspace = true
dragonfly-client-util.workspace = true
dragonfly-api.workspace = true
chrono.workspace = true
reqwest.workspace = true
rocksdb.workspace = true
serde.workspace = true
tracing.workspace = true
prost-wkt-types.workspace = true
tokio.workspace = true
tokio-util.workspace = true
sha2.workspace = true
crc.workspace = true
base16ct.workspace = true
fs2.workspace = true
lru.workspace = true
bytes.workspace = true
num_cpus = "1.0"
bincode = "1.3.3"
rayon = "1.10.0"

[dev-dependencies]
tempdir = "0.3"
